version: '3.4'
 
services: 
 
  frontend:
    image: afroissant20211126.azurecr.io/frontend:1.0
    build:
      context: frontend
      dockerfile: Dockerfile
    environment: 
      - backendUrl=http://backend
    ports:
      - "5902:80"
    depends_on: 
      - backend
  backend:
    image: afroissant20211126.azurecr.io/backend:1.0
    build: 
      context: backend
      dockerfile: Dockerfile
    ports: 
      - "5900:80"