version: '3.4'
 
services: 
 
  frontend:
    image: containerregistryazc20211126.azurecr.io/frontend:1.0
    environment: 
      - backendUrl=http://backend
    ports:
      - "80:80"
    depends_on: 
      - backend
  backend:
    image: containerregistryazc20211126.azurecr.io/backend:1.0
    ports: 
      - "80:80"